stages:
  dataset:
    cmd: python src/dataset.py data/raw/Train.csv
    deps:
      - data/raw/Train.csv
      - src/dataset.py
      - params.yaml
    params:
      - dataset.test_split
      - dataset.seed
    outs:
      - data/interim/train.csv
      - data/interim/test.csv

  train:
    cmd: python src/modeling/train.py data/interim/train.csv data/interim/test.csv
    deps:
      - data/interim/train.csv
      - data/interim/test.csv
      - src/modeling/train.py
      - params.yaml
    params:
      - train.n_estimators
      - train.learning_rate
      - train.max_depth
      - train.subsample
      - train.colsample_bytree
      - train.seed
      - train.reg_lambda
      - train.reg_alpha
    outs:
      - models/
    metrics:
      - metrics.json
